language: python

python:
  - 3.6

cache: pip

install: python setup.py install

script: python setup.py test

deploy:
  provider: pypi
  user: lbolla
  python: 3.6
  password:
    secure: "Pz7WaZob9BMD+Wm77KeiGnu6nUAoJSJYh0jASIXYd2SIcXEUYTkfSng5e1rEmJ+BVxPrZzAc5TVEaliNZdizVKv+tnpR7MPu9gJKXKkI8ivCvAAEckrIS5itP1Qslq18uOgNMV/XbjiFnvW5yHVYS1C5jyiatYmvQGAc9vc4v1V+SfVUQITtCuVH8eoe96TTpgEcPGx9YEccePY2D6YxtfCkZTC9r+S01p55P3VPbl4YYUxUGGfuO7mNqwPzhdMzKDCUwfLC+BhqDA3SNqxg0xrr4yQq2wA/rEKcdZrolWd6xYnYdtpMlzMdJLebv275LWOWiw/uIAewJ02vSEth5nJGSEv5KS1rBgfxiBn3PVrA+XUB/5KNR8l6OHLIIqcnzsu4gSQySaQZ3t03koNEALRn9dkKXCkSsHskT85cvBROnsmt9Yw2JfnTuWbER7D4JK6VF70g6Its6TnCSaN3w51cQD59Yn8vcDA8D3xS0f5G/pQOEiD0hH6ade7clYZqfz4QiJWMRKDFuufXAxeNDSnvqsFJ5CmaLtMXVJCsxg23mYHCCxtcRTSU0cXIlPv5Qj09WD5M48nx0ra1DpToH6OT6B+fWpbrqZAolDByjkDZvIAaDUwoEkt4U0XQsGLWp5G20WT7Ut/IJnVby6jLgb3qzCprpX+w2737hYIALgM="
  on:
    tags: true
